import Head from "next/head"
import MatchesList from "@/components/MatchesList/MatchesList"
import styles from '@/styles/Matches.module.css'


export default function Matches() {
    return(
        <>  
      <Head>
        <title>CSGO Ranking</title>
        <meta name="description" content="Generated by create next app" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <meta name="viewport" content="width=1024"/>       
      </Head>      
      <main className={styles.main}>    
      <MatchesList/>
      </main>
        </>
    )
}