import Head from 'next/head'
import styles from '@/styles/Home.module.css'

export default function Home() {

  return (   
    <>
      <Head>
        <title>CSGO Ranking</title>
        <meta name="description" content="Generated by create next app" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <meta name="viewport" content="width=1024"/>       
      </Head>      

      <main className={styles.main}>
      <h1>Home</h1>
      <h1>Coming Soon!</h1>
      </main>
 
    </>
  )
}

