import Head from 'next/head'
import styles from '@/styles/TopTeams.module.css'
import RankingList from '@/components/RankingList/RankingList';


export default function Ranking() {

  return (   
    <>  
      <Head>
        <title>CSGO Ranking</title>
        <meta name="description" content="Generated by create next app" />
        {/* <meta name="viewport" content="width=device-width, initial-scale=1" /> */}
        <meta name="viewport" content="width=1024"/>       
      </Head>      

      <main className={styles.main}>    

      <RankingList/>
      </main>
 
    </>
  )
}

